import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-900">
        <header>
          <h1 className="text-blue-700">TODO</h1>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
